version: "3.0"

expectations:
  population_size: 50000

actions:

  2017:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2017
    outputs:
      highly_sensitive:
        cohort: output/input_2017.csv

  2017_ckd:
    run: stata-mp:latest analysis/2017_ckd.do
    needs: [2017]
    outputs:
      highly_sensitive:
        analysis_dataset: output/2017_ckd.csv
      moderately_sensitive:
        log: logs/2017_ckd.log
  
  2017_ckd_complete:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_2017_ckd_complete
    needs: [2017, 2017_ckd]
    outputs:
      highly_sensitive:
        cohort: output/input_2017_ckd_complete.csv

  2017_clean_ckd_complete:
    run: stata-mp:latest analysis/2017_ckd_complete.do
    needs: [2017, 2017_ckd, 2017_ckd_complete]
    outputs:
      highly_sensitive:
        analysis_dataset: output/2017_ckd_complete.dta
      moderately_sensitive:
        log: logs/2017_ckd_complete.log

  2017_outcomes:
    run: stata-mp:latest analysis/2017_outcomes.do
    needs: [2017, 2017_ckd, 2017_ckd_complete, 2017_clean_ckd_complete]
    outputs:
      moderately_sensitive:
        log: logs/2017_outcomes.log
