version: "3.0"

expectations:
  population_size: 1000

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset --output dataset.csv.gz dataset_definition.py
    outputs:
      highly_sensitive:
        dataset: dataset.csv.gz
