# We set the line length to 60 characters because this is what the GitHub documentation
# style guide recommends for lines in code samples.
# https://docs.github.com/en/contributing/style-guide-and-content-model/style-guide#code

[tool.ruff]
line-length = 60

[tool.black]
line-length = 60
