---
title: "Absolute healthcare use (CKD stage 3)"
output: html_document
output_dir: "C:/Users/lsh1703468/Documents/Repo/ckd-healthcare-use/results"
output_file: "absolute_healthcare_use_ckd3.html"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

## Import libraries
library('tidyverse')
library('kableExtra')
library('cowplot')
library('scales')
```

```{r}
setwd("C:/Users/lsh1703468/Dropbox/PhD/health economics/figures")
### Annual healthcare use (restricted to OPD, ED & GP)
palette <- c("#3B9AB2", "#EBCC2A", "#E1AF00", "#B40F20", "#5DBB63", "#FF5733", "#FFC300", "#FF8C00", "#CD5C5C", "#FF1493", "#9370DB", "#6A5ACD")

# Read in data
d <- read.csv("absolute_healthcare_use_ckd3.csv", sep = "\t", na.strings = "N/A")
d$date <- as.Date(d$date, format = "%d/%m/%Y")

# Create stacked dataframe with 1 row per data point
d1 <- rbind(
  d %>% mutate(count = ip, outcome = "Inpatient days"),
  d %>% mutate(count = icu, outcome = "ICU days"),
  d %>% mutate(count = ed, outcome = "ED presentations"),
  d %>% mutate(count = opd, outcome = "Outpatient appointments"),
  d %>% mutate(count = neph, outcome = "Nephrology appointments"),
  d %>% mutate(count = gp, outcome = "GP interactions"),
  d %>% mutate(count = bp, outcome = "Blood pressure measurements"),
  d %>% mutate(count = uacr, outcome = "uACR measurements"),
  d %>% mutate(count = scr, outcome = "SCr measurements")
) %>%
  # select variables of interest
  select(date, count, outcome)

# Change date coding
d1$Date_factor <- factor(d1$date)
d1$Date_factor <- recode_factor(d1$Date_factor, "2017-04-01" = "2016/17", "2018-04-01" = "2017/18", "2019-04-01" = "2018/19", "2020-04-01" = "2019/20", "2021-04-01" = "2020/21", "2022-04-01" = "2021/22") 
```

<b>[Inpatient days]{style="font-size: 20px;"}</b>

```{r, fig.width=8, fig.height=3, message=FALSE}
# Filter the data for "Inpatient days"
d2_ip <- d1 %>%
  filter(outcome == "Inpatient days")

plot_ymax = max(d2_ip$count, na.rm=T)*1.2

# Generate plot
ggplot(d2_ip, aes(x = date, y = count)) + 
  geom_line(size = 0.8) + 
  ylab("Inpatient days") + 
  xlab("Year") +
  labs(colour = "Inpatient days") +
  scale_colour_manual(values = palette) +
  scale_fill_manual(values = palette, guide = FALSE) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +  # Specify date breaks and format
  scale_y_continuous(labels = scales::comma, limits = c(0, plot_ymax)) +
  theme_bw() + 
  theme(legend.position = "right", 
        axis.text = element_text(size = 10), 
        axis.title = element_text(size = 10),
        legend.title = element_text(size = 10), 
        legend.text = element_text(size = 10),
        axis.text.x = element_text(size = 10, hjust = 0),  # Center x-axis labels
        axis.ticks.x = element_blank()  # Remove x-axis ticks
  )
```

<b>[ICU days]{style="font-size: 20px;"}</b>

```{r, fig.width=8, fig.height=3, message=FALSE}
# Filter the data for "ICU days"
d2_icu <- d1 %>%
  filter(outcome == "ICU days")

plot_ymax = max(d2_icu$count, na.rm=T)*1.2

# Generate plot
ggplot(d2_icu, aes(x = date, y = count)) + 
  geom_line(size = 0.8) + 
  ylab("ICU days") + 
  xlab("Year") +
  labs(colour = "ICU days") +
  scale_colour_manual(values = palette) +
  scale_fill_manual(values = palette, guide = FALSE) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +  # Specify date breaks and format
  scale_y_continuous(labels = scales::comma, limits = c(0, plot_ymax)) +
  theme_bw() + 
  theme(legend.position = "right", 
        axis.text = element_text(size = 10), 
        axis.title = element_text(size = 10),
        legend.title = element_text(size = 10), 
        legend.text = element_text(size = 10),
        axis.text.x = element_text(size = 10, hjust = 0),  # Center x-axis labels
        axis.ticks.x = element_blank()  # Remove x-axis ticks
  )
```

<b>[ED presentations]{style="font-size: 20px;"}</b>

```{r, fig.width=8, fig.height=3, message=FALSE}
# Convert the "Date" column to a Date object
d1$date <- as.Date(d1$date, format = "%Y_%m_%d")

# Filter the data for "ED presentations" and Date not equal to the specified date
d2_ed <- d1 %>%
  filter(outcome == "ED presentations", !date == as.Date("2017-04-01"))

plot_ymax = max(d2_ed$count, na.rm=T)*1.2

# Generate plot
ggplot(d2_ed, aes(x = date, y = count)) + 
  geom_line(size = 0.8) + 
  ylab("ED presentations") + 
  xlab("Year") +
  labs(colour = "ED presentations") +
  scale_colour_manual(values = palette) +
  scale_fill_manual(values = palette, guide = FALSE) +
  scale_x_continuous(
    breaks = seq(as.Date("2017-04-01"), as.Date("2022-04-01"), by = "1 year"),  # Specify breaks
    labels = date_format("%Y")  # Format labels as years
  ) +
  theme_bw() + 
  scale_y_continuous(labels = scales::comma, limits = c(0, plot_ymax)) +
  theme(legend.position = "right", 
        axis.text = element_text(size = 10), 
        axis.title = element_text(size = 10),
        legend.title = element_text(size = 10), 
        legend.text = element_text(size = 10),
        axis.text.x = element_text(size = 10, hjust = 0.5),  # Center x-axis labels
        axis.ticks.x = element_blank()  # Remove x-axis ticks
  )
```


<b>[Outpatient appointments]{style="font-size: 20px;"}</b>

```{r, fig.width=8, fig.height=3, message=FALSE}
# Convert the "Date" column to a Date object
d1$date <- as.Date(d1$date, format = "%Y_%m_%d")

# Filter the data for "Outpatient appointments" and Date not equal to the specified date
d2_opd <- d1 %>%
  filter(outcome == "Outpatient appointments", !date == as.Date("2017-04-01"), !date == as.Date("2018-04-01"))

plot_ymax = max(d2_opd$count, na.rm=T)*1.2

# Generate plot
ggplot(d2_opd, aes(x = date, y = count)) + 
  geom_line(size = 0.8) + 
  ylab("Outpatient appointments") + 
  xlab("Year") +
  labs(colour = "Outpatient appointments") +
  scale_colour_manual(values = palette) +
  scale_fill_manual(values = palette, guide = FALSE) +
  scale_x_continuous(
    breaks = seq(as.Date("2018-04-01"), as.Date("2022-04-01"), by = "1 year"),  # Specify breaks
    labels = date_format("%Y")  # Format labels as years
  ) +
  theme_bw() + 
  scale_y_continuous(labels = scales::comma, limits = c(0, plot_ymax)) +
  theme(legend.position = "right", 
        axis.text = element_text(size = 10), 
        axis.title = element_text(size = 10),
        legend.title = element_text(size = 10), 
        legend.text = element_text(size = 10),
        axis.text.x = element_text(size = 10, hjust = 0.5),  # Center x-axis labels
        axis.ticks.x = element_blank()  # Remove x-axis ticks
  )
```

<b>[Nephrology appointments]{style="font-size: 20px;"}</b>

```{r, fig.width=8, fig.height=3, message=FALSE}
# Convert the "Date" column to a Date object
d1$date <- as.Date(d1$date, format = "%Y_%m_%d")

# Filter the data for "Nephrology appointments" and Date not equal to the specified date
d2_neph <- d1 %>%
  filter(outcome == "Nephrology appointments", !date == as.Date("2017-04-01"), !date == as.Date("2018-04-01"))

plot_ymax = max(d2_neph$count, na.rm=T)*1.2

# Generate plot
ggplot(d2_neph, aes(x = date, y = count)) + 
  geom_line(size = 0.8) + 
  ylab("Nephrology appointments") + 
  xlab("Year") +
  labs(colour = "Nephrology appointments") +
  scale_colour_manual(values = palette) +
  scale_fill_manual(values = palette, guide = FALSE) +
  scale_x_continuous(
    breaks = seq(as.Date("2018-04-01"), as.Date("2022-04-01"), by = "1 year"),  # Specify breaks
    labels = date_format("%Y")  # Format labels as years
  ) +
  theme_bw() + 
  scale_y_continuous(labels = scales::comma, limits = c(0, plot_ymax)) +
  theme(legend.position = "right", 
        axis.text = element_text(size = 10), 
        axis.title = element_text(size = 10),
        legend.title = element_text(size = 10), 
        legend.text = element_text(size = 10),
        axis.text.x = element_text(size = 10, hjust = 0.5),  # Center x-axis labels
        axis.ticks.x = element_blank()  # Remove x-axis ticks
  )
```

<b>[GP interactions]{style="font-size: 20px;"}</b>

```{r, fig.width=8, fig.height=3, message=FALSE}
# Filter the data for "GP interactions"
d2_gp <- d1 %>%
  filter(outcome == "GP interactions")

plot_ymax = max(d2_gp$count, na.rm=T)*1.2

# Generate plot
ggplot(d2_gp, aes(x = date, y = count)) + 
  geom_line(size = 0.8) + 
  ylab("GP interactions") + 
  xlab("Year") +
  labs(colour = "GP interactions") +
  scale_colour_manual(values = palette) +
  scale_fill_manual(values = palette, guide = FALSE) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +  # Specify date breaks and format
  scale_y_continuous(labels = scales::comma, limits = c(0, plot_ymax)) +
  theme_bw() + 
  theme(legend.position = "right", 
        axis.text = element_text(size = 10), 
        axis.title = element_text(size = 10),
        legend.title = element_text(size = 10), 
        legend.text = element_text(size = 10),
        axis.text.x = element_text(size = 10, hjust = 0),  # Center x-axis labels
        axis.ticks.x = element_blank()  # Remove x-axis ticks
  )
```

<b>[Blood pressure measurements]{style="font-size: 20px;"}</b>

```{r, fig.width=8, fig.height=3, message=FALSE}
# Filter the data for "Blood pressure measurements"
d2_bp <- d1 %>%
  filter(outcome == "Blood pressure measurements")

plot_ymax = max(d2_bp$count, na.rm=T)*1.2

# Generate plot
ggplot(d2_bp, aes(x = date, y = count)) + 
  geom_line(size = 0.8) + 
  ylab("Blood pressure measurements") + 
  xlab("Year") +
  labs(colour = "Blood pressure measurements") +
  scale_colour_manual(values = palette) +
  scale_fill_manual(values = palette, guide = FALSE) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +  # Specify date breaks and format
  scale_y_continuous(labels = scales::comma, limits = c(0, plot_ymax)) +
  theme_bw() + 
  theme(legend.position = "right", 
        axis.text = element_text(size = 10), 
        axis.title = element_text(size = 10),
        legend.title = element_text(size = 10), 
        legend.text = element_text(size = 10),
        axis.text.x = element_text(size = 10, hjust = 0),  # Center x-axis labels
        axis.ticks.x = element_blank()  # Remove x-axis ticks
  )
```

<b>[uACR measurements]{style="font-size: 20px;"}</b>

```{r, fig.width=8, fig.height=3, message=FALSE}
# Filter the data for "uACR measurements"
d2_uacr <- d1 %>%
  filter(outcome == "uACR measurements")

plot_ymax = max(d2_uacr$count, na.rm=T)*1.2

# Generate plot
ggplot(d2_uacr, aes(x = date, y = count)) + 
  geom_line(size = 0.8) + 
  ylab("uACR measurements") + 
  xlab("Year") +
  labs(colour = "uACR measurements") +
  scale_colour_manual(values = palette) +
  scale_fill_manual(values = palette, guide = FALSE) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +  # Specify date breaks and format
  scale_y_continuous(labels = scales::comma, limits = c(0, plot_ymax)) +
  theme_bw() + 
  theme(legend.position = "right", 
        axis.text = element_text(size = 10), 
        axis.title = element_text(size = 10),
        legend.title = element_text(size = 10), 
        legend.text = element_text(size = 10),
        axis.text.x = element_text(size = 10, hjust = 0),  # Center x-axis labels
        axis.ticks.x = element_blank()  # Remove x-axis ticks
  )
```

<b>[SCr measurements]{style="font-size: 20px;"}</b>

```{r, fig.width=8, fig.height=3, message=FALSE}
# Filter the data for "SCr measurements"
d2_scr <- d1 %>%
  filter(outcome == "SCr measurements")

plot_ymax = max(d2_scr$count, na.rm=T)*1.2

# Generate plot
ggplot(d2_scr, aes(x = date, y = count)) + 
  geom_line(size = 0.8) + 
  ylab("SCr measurements") + 
  xlab("Year") +
  labs(colour = "SCr measurements") +
  scale_colour_manual(values = palette) +
  scale_fill_manual(values = palette, guide = FALSE) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +  # Specify date breaks and format
  scale_y_continuous(labels = scales::comma, limits = c(0, plot_ymax)) +
  theme_bw() + 
  theme(legend.position = "right", 
        axis.text = element_text(size = 10), 
        axis.title = element_text(size = 10),
        legend.title = element_text(size = 10), 
        legend.text = element_text(size = 10),
        axis.text.x = element_text(size = 10, hjust = 0),  # Center x-axis labels
        axis.ticks.x = element_blank()  # Remove x-axis ticks
  )
```